#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Modality-Invariant ViT (vit_small_patch16_224) for Skin Disease Classification
Uses multi-objective losses: Lcls, Lconf, Lcon, LMI.

All outputs (checkpoints, results, logs) are saved in:
    - checkpoints_modality_vit/
    - results_modality_vit/
"""

import sys
import random
import math
import json
import shutil
from pathlib import Path
from collections import defaultdict
import warnings

import numpy as np
import pandas as pd
from tqdm import tqdm

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, WeightedRandomSampler

from models.models_losses import (
    DualViT,
    SupConLoss,
    confusion_loss,
    skin_type_loss,
    mi_loss,
    mixup_embeddings,
    cls_loss_fn,
    compute_class_weights,
    get_layer_wise_lr_params_vit,   # ViT‑specific layer‑wise LR decay
)
from models.evaluation import (
    validate,
    fairness,
    save_results_csv,
    plot_confusion_matrix,
    plot_per_class_metrics,
    plot_fairness_metrics,
    plot_training_curves,
    plot_tsne,
    build_loaders,       # same unified loader builder
    LABEL_NAMES,
)

warnings.filterwarnings("ignore")

# ------------------------------------------------------------
# Configuration – edit these as needed
# ------------------------------------------------------------
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Device: {DEVICE}")

# ============================================================
# PATH CONFIGURATION  — update these for each environment
# ============================================================

# Working directory: checkpoints and results will be created as subdirs here
WORK_ROOT = Path('/kaggle/working/modality-invariance/process/process/outputs')

# Directory that contains the CSVs generated by data_preprocessing.ipynb
# (paired_train.csv, clin_train.csv, derm_train.csv, eval_derm7pt.csv, ...)
CSV_DIR = WORK_ROOT / 'csvs'

# Root directories for each raw dataset.
# The Dataset classes use these together with the image_id column in the CSVs
# to resolve full image paths at load time (see evaluation.py / build_loaders).
DATASET_ROOTS = {
    'hiba':           Path('/kaggle/input/datasets/asosenge/hibaskinlesionsdataset-main'),
    'fitzpatrick17k': Path('/kaggle/input/datasets/asosenge/fitzpatrick17k'),
    'ham10000':       Path('/kaggle/input/datasets/asosenge/ham10000'),
    'derm7pt':        Path('/kaggle/input/datasets/asosenge/derm7pt'),
}

# Verify paths exist and warn early rather than failing mid-training
print("Checking configured paths:")
print(f"  WORK_ROOT : {WORK_ROOT}  {'[OK]' if WORK_ROOT.exists() else '[MISSING]'}")
print(f"  CSV_DIR   : {CSV_DIR}  {'[OK]' if CSV_DIR.exists() else '[MISSING]'}")
for name, root in DATASET_ROOTS.items():
    print(f"  {name:<15}: {root}  {'[OK]' if root.exists() else '[MISSING — update DATASET_ROOTS]'}")

CFG = {
    # Preprocessed CSV directory
    'csv_dir':       CSV_DIR,
    # Per-dataset image roots (passed to build_loaders for image_id → path resolution)
    'dataset_roots': DATASET_ROOTS,
    # Output directories
    'ckpt_dir':      WORK_ROOT / 'checkpoints_modality_vit',
    'results_dir':   WORK_ROOT / 'results_modality_vit',

    # Architecture
    'backbone': 'vit_small_patch16_224',
    'embed_dim': 512,
    'img_size': 224,
    'num_classes': 5,
    'num_skin_types': 6,

    # Training
    'batch_size': 32,
    'num_epochs': 1,
    'lr': 3e-5,
    'min_lr': 1e-6,
    'weight_decay': 0.05,
    'warmup_epochs': 1,
    'aug_probability': 0.85,

    # Loss weights
    'lambda_cls': 1.0,
    'lambda_conf': 1.0,
    'lambda_con': 1.0,
    'lambda_mi': 1.5,
    'temperature': 0.07,
    'label_smoothing': 0.1,
    'mixup_alpha': 0.4,

    # Flags – all enabled for full model
    'use_conf': True,
    'use_con': True,
    'use_mi': True,
    'use_mixup': True,
}

# Create output directories
CFG["ckpt_dir"].mkdir(parents=True, exist_ok=True)
CFG["results_dir"].mkdir(parents=True, exist_ok=True)


# ------------------------------------------------------------
# Training epoch function (uses imported losses)
# ------------------------------------------------------------
def train_epoch(model, loader, optimizer, cfg, epoch, scaler, class_weights, device):
    model.train()
    totals = dict(total=0., cls=0., conf=0., skin=0., con=0., mi=0.)
    all_preds, all_labels = [], []
    n_batches = 0

    sup_con = SupConLoss(cfg["temperature"]).to(device)
    weight_tensor = torch.tensor(class_weights, dtype=torch.float32, device=device) if class_weights else None

    pbar = tqdm(loader, desc=f"Ep {epoch+1:>3} [train]", unit="batch", dynamic_ncols=True, leave=False)
    for batch in pbar:
        # Move tensors to device
        for k, v in batch.items():
            if isinstance(v, torch.Tensor):
                batch[k] = v.to(device, non_blocking=True)

        optimizer.zero_grad(set_to_none=True)

        with torch.cuda.amp.autocast(enabled=(device.type == "cuda")):
            out = model(batch)
            labels = batch["label"]
            skin_types = batch["skin_type"]

            # Lcls with optional mixup
            use_mixup = cfg.get("use_mixup", True)
            if use_mixup and out["z"].requires_grad:
                z_mix, y_a, y_b, lam = mixup_embeddings(out["z"], labels, alpha=cfg["mixup_alpha"])
                logits_mix = model.classifier(z_mix)
                loss_cls = lam * cls_loss_fn(logits_mix, y_a, weight_tensor, cfg["label_smoothing"]) \
                           + (1.0 - lam) * cls_loss_fn(logits_mix, y_b, weight_tensor, cfg["label_smoothing"])
            else:
                loss_cls = cls_loss_fn(out["logits"], labels, weight_tensor, cfg["label_smoothing"])

            loss_conf = confusion_loss(out["skin_logits"]) if cfg.get("use_conf") else 0.0
            loss_skin = skin_type_loss(model.skin_clf(out["z"].detach()), skin_types) if cfg.get("use_conf") else 0.0
            loss_con = sup_con(out["z"], labels) if cfg.get("use_con") else 0.0
            loss_mi = mi_loss(out["z_c"], out["z_d"]) if (cfg.get("use_mi") and "z_c" in out and out["z_c"].size(0) > 0) else 0.0

            total_loss = cfg["lambda_cls"] * loss_cls
            if cfg.get("use_conf"):
                total_loss += cfg["lambda_conf"] * loss_conf + loss_skin
            if cfg.get("use_con"):
                total_loss += cfg["lambda_con"] * loss_con
            if cfg.get("use_mi") and loss_mi != 0:
                total_loss += cfg["lambda_mi"] * loss_mi

        scaler.scale(total_loss).backward()
        scaler.unscale_(optimizer)
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        scaler.step(optimizer)
        scaler.update()

        totals["total"] += total_loss.item()
        totals["cls"] += loss_cls.item() if isinstance(loss_cls, torch.Tensor) else loss_cls
        totals["conf"] += loss_conf.item() if isinstance(loss_conf, torch.Tensor) else loss_conf
        totals["skin"] += loss_skin.item() if isinstance(loss_skin, torch.Tensor) else loss_skin
        totals["con"] += loss_con.item() if isinstance(loss_con, torch.Tensor) else loss_con
        totals["mi"] += loss_mi.item() if isinstance(loss_mi, torch.Tensor) else loss_mi
        n_batches += 1

        with torch.no_grad():
            preds = out["logits"].argmax(dim=1).cpu().numpy()
        all_preds.append(preds)
        all_labels.append(batch["label"].cpu().numpy())

        pbar.set_postfix(loss=f"{totals['total']/n_batches:.4f}")

    pbar.close()
    for k in totals:
        totals[k] /= max(n_batches, 1)
    all_preds = np.concatenate(all_preds)
    all_labels = np.concatenate(all_labels)
    totals["acc"] = (all_preds == all_labels).mean()
    totals["macro_f1"] = f1_score(all_labels, all_preds, average="macro", zero_division=0)
    return totals


# ------------------------------------------------------------
# Main training and evaluation pipeline
# ------------------------------------------------------------
def main():
    print(f"CSV dir      : {CFG['csv_dir']}")
    print(f"Checkpoints  : {CFG['ckpt_dir']}")
    print(f"Results      : {CFG['results_dir']}")
    print("Dataset roots:")
    for name, root in CFG['dataset_roots'].items():
        print(f"  {name:<15}: {root}")

    # Build data loaders (reusing the common builder).
    # build_loaders uses CFG['dataset_roots'] to resolve image_id → full path.
    train_loader, val_loader, test_loader, eval_loaders = build_loaders(CFG, seed=SEED)
    print(f"Train batches: {len(train_loader)}, Val batches: {len(val_loader)}")
    if test_loader:
        print(f"Test batches: {len(test_loader)}")
    print(f"Cross-eval loaders: {list(eval_loaders.keys())}")

    # Compute class weights
    class_weights = compute_class_weights(CFG["csv_dir"], CFG["num_classes"])
    if class_weights:
        print(f"Class weights: {np.round(class_weights, 3)}")
    else:
        class_weights = None

    # Model – use_projection=True for contrastive learning
    model = DualViT(
        embed_dim=CFG["embed_dim"],
        num_classes=CFG["num_classes"],
        num_skin_types=CFG["num_skin_types"],
        pretrained=True,
        use_projection=True,
    ).to(DEVICE)

    # Optimizer with layer‑wise LR decay for ViT (blocks)
    param_groups = get_layer_wise_lr_params_vit(model, base_lr=CFG["lr"], lr_decay=0.85)
    optimizer = torch.optim.AdamW(param_groups, weight_decay=CFG["weight_decay"], betas=(0.9, 0.999), eps=1e-8)

    # Cosine annealing scheduler with warmup
    def lr_lambda(epoch):
        if epoch < CFG["warmup_epochs"]:
            return (epoch + 1) / CFG["warmup_epochs"]
        progress = (epoch - CFG["warmup_epochs"]) / max(1, CFG["num_epochs"] - CFG["warmup_epochs"])
        cos = 0.5 * (1 + math.cos(math.pi * progress))
        min_frac = CFG["min_lr"] / CFG["lr"]
        return max(min_frac, cos)

    scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer, lr_lambda)
    scaler = torch.cuda.amp.GradScaler(enabled=(DEVICE.type == "cuda"))

    # Resume if requested (optional)
    start_epoch = 0
    best_auroc = 0.0
    best_f1 = 0.0
    history = defaultdict(list)

    # (Resume code can be added here if needed – omitted for brevity)

    # Training loop
    for epoch in range(start_epoch, CFG["num_epochs"]):
        train_metrics = train_epoch(model, train_loader, optimizer, CFG, epoch, scaler, class_weights, DEVICE)
        scheduler.step()
        val_metrics = validate(model, val_loader, DEVICE, CFG["num_classes"])
        lr = optimizer.param_groups[0]["lr"]

        # Update history
        for k, v in train_metrics.items():
            history[f"train_{k}"].append(float(v))
        for k in ["acc", "auroc", "macro_f1", "weighted_f1"]:
            history[f"val_{k}"].append(float(val_metrics[k]))
        history["lr"].append(float(lr))

        print(f"Ep {epoch+1:3d}/{CFG['num_epochs']}  "
              f"loss={train_metrics['total']:.4f}  tr_acc={train_metrics['acc']:.4f}  "
              f"val_acc={val_metrics['acc']:.4f}  val_auroc={val_metrics['auroc']:.4f}  "
              f"val_f1={val_metrics['macro_f1']:.4f}  lr={lr:.2e}")

        # Checkpointing
        ckpt_state = {
            "epoch": epoch,
            "model": model.state_dict(),
            "optimizer": optimizer.state_dict(),
            "scheduler": scheduler.state_dict(),
            "history": dict(history),
        }
        torch.save(ckpt_state, CFG["ckpt_dir"] / "last_model.pt")
        if not np.isnan(val_metrics["auroc"]) and val_metrics["auroc"] > best_auroc:
            best_auroc = val_metrics["auroc"]
            shutil.copy(CFG["ckpt_dir"] / "last_model.pt", CFG["ckpt_dir"] / "best_auroc_model.pt")
        if val_metrics["macro_f1"] > best_f1:
            best_f1 = val_metrics["macro_f1"]
            shutil.copy(CFG["ckpt_dir"] / "last_model.pt", CFG["ckpt_dir"] / "best_f1_model.pt")
        if (epoch + 1) % 5 == 0:
            torch.save(ckpt_state, CFG["ckpt_dir"] / f"checkpoint_ep{epoch+1:03d}.pt")

        with open(CFG["results_dir"] / "history.json", "w") as f:
            json.dump({k: [float(x) for x in v] for k, v in history.items()}, f, indent=2)

    print(f"Training complete. Best AUROC: {best_auroc:.4f}, Best F1: {best_f1:.4f}")

    # Load best model
    best_ckpt = CFG["ckpt_dir"] / "best_f1_model.pt"
    if not best_ckpt.exists():
        best_ckpt = CFG["ckpt_dir"] / "best_auroc_model.pt"
    if not best_ckpt.exists():
        best_ckpt = CFG["ckpt_dir"] / "last_model.pt"
    ckpt = torch.load(best_ckpt, map_location=DEVICE, weights_only=False)
    model.load_state_dict(ckpt["model"])
    print(f"Loaded best model from {best_ckpt.name} (epoch {ckpt['epoch']+1})")

    # Evaluation
    val_res = validate(model, val_loader, DEVICE, CFG["num_classes"])
    val_fair = fairness(val_res)
    save_results_csv(val_res, val_fair, "val", CFG["results_dir"], LABEL_NAMES)
    plot_confusion_matrix(val_res["conf_mat"], [LABEL_NAMES[i] for i in range(CFG["num_classes"])],
                          "Confusion Matrix - Validation", CFG["results_dir"] / "val_confusion.png")
    plot_per_class_metrics(val_res, [LABEL_NAMES[i] for i in range(CFG["num_classes"])],
                           "Per-Class Metrics - Validation", CFG["results_dir"] / "val_per_class.png")
    plot_fairness_metrics(val_fair, "Fairness - Validation", CFG["results_dir"] / "val_fairness.png")

    if test_loader:
        test_res = validate(model, test_loader, DEVICE, CFG["num_classes"])
        test_fair = fairness(test_res)
        save_results_csv(test_res, test_fair, "test", CFG["results_dir"], LABEL_NAMES)
        plot_confusion_matrix(test_res["conf_mat"], [LABEL_NAMES[i] for i in range(CFG["num_classes"])],
                              "Confusion Matrix - Test", CFG["results_dir"] / "test_confusion.png")
        plot_per_class_metrics(test_res, [LABEL_NAMES[i] for i in range(CFG["num_classes"])],
                               "Per-Class Metrics - Test", CFG["results_dir"] / "test_per_class.png")
        plot_fairness_metrics(test_fair, "Fairness - Test", CFG["results_dir"] / "test_fairness.png")

    # Cross-dataset evaluation
    cross_results = {}
    for ds_name, loader in eval_loaders.items():
        print(f"\nEvaluating on {ds_name}")
        res = validate(model, loader, DEVICE, CFG["num_classes"])
        fair = fairness(res)
        save_results_csv(res, fair, f"cross_{ds_name}", CFG["results_dir"], LABEL_NAMES)
        plot_confusion_matrix(res["conf_mat"], [LABEL_NAMES[i] for i in range(CFG["num_classes"])],
                              f"Confusion Matrix - {ds_name}", CFG["results_dir"] / f"cross_{ds_name}_confusion.png")
        plot_per_class_metrics(res, [LABEL_NAMES[i] for i in range(CFG["num_classes"])],
                               f"Per-Class Metrics - {ds_name}", CFG["results_dir"] / f"cross_{ds_name}_per_class.png")
        plot_fairness_metrics(fair, f"Fairness - {ds_name}", CFG["results_dir"] / f"cross_{ds_name}_fairness.png")
        cross_results[ds_name] = {
            "accuracy": res["acc"],
            "auroc": res["auroc"],
            "macro_f1": res["macro_f1"],
            "EOM": fair["EOM"],
            "PQD": fair["PQD"],
            "DPM": fair["DPM"],
        }
    if cross_results:
        cross_df = pd.DataFrame(cross_results).T
        cross_df.to_csv(CFG["results_dir"] / "cross_dataset_summary.csv")
        print("\nCross-dataset summary:\n", cross_df)

    # Training curves
    plot_training_curves(history, "Training History (Modality-Invariant ViT)",
                         CFG["results_dir"] / "training_curves.png")

    # t-SNE on test set
    if test_loader:
        model.eval()
        all_embs, all_labels_tsne = [], []
        with torch.no_grad():
            for batch in test_loader:
                for k, v in batch.items():
                    if isinstance(v, torch.Tensor):
                        batch[k] = v.to(DEVICE)
                out = model(batch)
                all_embs.append(out["z"].cpu().numpy())
                all_labels_tsne.append(batch["label"].cpu().numpy())
        embs = np.concatenate(all_embs)
        labels_tsne = np.concatenate(all_labels_tsne)
        plot_tsne(embs, labels_tsne, "t-SNE - Test Set", CFG["results_dir"] / "tsne_test.png")

    print(f"\nAll results saved to {CFG['results_dir']}")
    print(f"Checkpoints saved to {CFG['ckpt_dir']}")


if __name__ == "__main__":
    main()